[project]
name = "TeamViewer-web-server"
version = "0.2.0"
description = "一个用于共享团队视野的服务端网页代码"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.129.0",
    "httpx[http2]>=0.28.1",
    "uvicorn[standard]>=0.40.0",
]
